name: order_app
description: "A new Flutter project." 
publish_to: 'none' 

 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

workspace:

  - packages/lib_base
  - packages/lib_domain
  # - packages/lib_resources
 
dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  flutter_secure_storage: any
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  get: ^4.6.5
  dio: ^5.7.0
  logger: ^2.5.0
  convert: ^3.1.1
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  path_provider: ^2.1.3
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  async: ^2.11.0
  encrypt: ^5.0.3
  flutter_image_compress: ^2.4.0
  build_runner: ^2.4.11
  marquee: ^2.3.0
  flutter_slidable: ^3.1.1


flutter:


  uses-material-design: true
  assets:
    - assets/


